version: "3.7"
services:
  pokedex:
    image: alimizan/pokedex
    build: .
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
    - target: 80
      published: 80
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf
